FROM tea.intra.kat.sh/koa/rocky:vm

RUN dnf -y update && \
    dnf -y config-manager --set-enabled powertools && \
    dnf -y install --allowerasing \
    munge       \
    munge-libs  \
    munge-devel \
    && dnf clean all

RUN export MUNGEUSER=1001 && \
    groupadd -g $MUNGEUSER munge && \
    useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge \ 
    -u $MUNGEUSER -g munge -s /sbin/nologin munge