FROM tea.intra.kat.sh/koa/rocky:10

# First, run the update
# We must use exec form: ["executable", "param1", "param2"]
RUN ["dnf", "-y", "update"]

# Next, run the install
# We list all packages in a single exec form command
RUN ["dnf", "-y", "install", "dnf-plugins-core", "epel-release", "kernel-headers", "qemu-guest-agent"]
