FROM docker.io/rockylinux/rockylinux:10

RUN dnf -y update && \
    dnf -y install --allowerasing 'dnf-command(config-manager)' epel-release && \
    dnf config-manager --set-enabled crb

RUN dnf update -y \
    && dnf upgrade -y --allowerasing

# Install kernel
RUN dnf install -y --setopt=install_weak_deps=False --allowerasing \
	kernel-core	\
	kernel-modules

# Install core tools/utils
RUN dnf install -y --setopt=install_weak_deps=False --allowerasing \
	coreutils	\
	ethtool		\
	findutils	\
#       ╰─| Xargs
	e2fsprogs	\
#	╰─| Needed for filesystems
	initscripts	\
	iproute		\
	net-tools	\
#       ╰─| arp
	NetworkManager	\
	nfs-utils	\
	pciutils	\
	psmisc		\
	rsyslog		\
	strace		\
	bash		

# Install feature depnencies
RUN dnf install -y --setopt=install_weak_deps=False --allowerasing \
    openssh-clients \
    openssh-server  \
	Lmod

# install QOL tools
RUN dnf install -y --setopt=install_weak_deps=False --allowerasing \
	which	\
	curl	\
	rsync

RUN dnf install  -y --setopt=install_weak_deps=False --allowerasing dnf-plugins-core dnf-automatic \
	&& dnf clean all

RUN systemctl enable dnf-automatic.timer

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061
# remove unused dynamic system user
RUN userdel systemd-oom && \
    userdel systemd-coredump

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/
RUN /etc/warewulf/container_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
