ame: Build images
run-name: ${{ gitea.actor }} Building warewulf images
on: [push]

jobs:
  build-warewulf-images:
    runs-on: carp
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set registry host environment variable
        run: echo "REGISTRY_HOST=$(echo $GITEA_INSTANCE | sed 's|https://||;s|http://||')" >> $GITEA_ENV
        env:
          GITEA_INSTANCE: ${{ gitea.instance }}

      - name: Log in to Gitea Container Registry
        # This step is still useful as it authenticates podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Find, Build, and Push All Containers
        run: |
          set -e # Exit immediately if a command fails
          
          # Set the base URL for your Gitea registry
          # Gitea variables like instance_url and owner are already lowercase
          REGISTRY_BASE="${{ env.REGISTRY_HOST }}/${{ gitea.repository_owner }}"
          
          # Get a lowercase version of the repo name for the root case
          REPO_NAME_LOWER=$(echo "${{ gitea.repository_name }}" | tr '[:upper:]' '[:lower:]')
          
          echo "Registry base URL: $REGISTRY_BASE"
          
          # Find all files named 'Containerfile' and loop through them
          find . -name Containerfile | while read -r cfile; do
              # Remove the leading './' for cleaner names
              cfile_clean=$(echo "$cfile" | sed 's|^\./||') # e.g., rocky/vm/Containerfile
              
              # Get the directory of the Containerfile (this is the build context)
              context_dir=$(dirname "$cfile_clean") # e.g., rocky/vm or .
              
              image_name=""
              image_tag=""

              # Check if this is the root Containerfile
              if [ "$context_dir" = "." ]; then
                  image_name="$REPO_NAME_LOWER"
                  image_tag="latest"
              else
                  # This is in a subdirectory
                  current_dir_name=$(basename "$context_dir") # e.g., vm or debian
                  parent_dir_path=$(dirname "$context_dir") # e.g., rocky or .

                  if [ "$parent_dir_path" = "." ]; then
                      # Top-level dir (e.g., debian/Containerfile)
                      # Image name is the dir name, tag is latest
                      image_name=$(echo "$current_dir_name" | tr '[:upper:]' '[:lower:]')
                      image_tag="latest"
                  else
                      # Sub-level dir (e.g., rocky/vm/Containerfile)
                      # Image name is parent dir, tag is current dir
                      image_name=$(echo "$(basename "$parent_dir_path")" | tr '[:upper:]' '[:lower:]')
                      image_tag=$(echo "$current_dir_name" | tr '[:upper:]' '[:lower:]')
                  fi
              fi
              
              # This is the full URL for the registry (e.g., gitea.example.com/owner/rocky:vm)
              IMAGE_URL="${REGISTRY_BASE}/${image_name}:${image_tag}"
              echo ""
              echo "================================================="
              echo "Found:      $cfile_clean"
              echo "Context:    $context_dir"
              echo "Building:   $IMAGE_URL"
              echo "================================================="
              
              # Build the image and tag it with the full registry URL
              podman build -t "$IMAGE_URL" -f "$cfile_clean" "$context_dir"
              
              echo "Pushing $IMAGE_URL"
              podman push "$IMAGE_URL"
              echo "================================================="
              echo ""
          done
          
          echo "All builds complete."
