name: Build images
run-name: ${{ gitea.actor }} Building warewulf images
on: [push]

jobs:
  build-warewulf-images:
    runs-on: carp
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Gitea Container Registry
        # This step is still useful as it authenticates podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ gitea.instance_url_no_protocol }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Find, Build, and Push All Containers
        run: |
          set -e # Exit immediately if a command fails
          
          # Set the base URL for your Gitea registry
          REGISTRY_BASE="${{ gitea.instance_url_no_protocol }}/${{ gitea.repository_owner }}"
          
          echo "Registry base URL: $REGISTRY_BASE"
          
          # Find all files named 'Containerfile' and loop through them
          find . -name Containerfile | while read -r cfile; do
              # Remove the leading './' for cleaner names
              cfile_clean=$(echo "$cfile" | sed 's|^\./||') # e.g., rocky/vm/Containerfile
              
              # Get the directory of the Containerfile (this is the build context)
              context_dir=$(dirname "$cfile_clean") # e.g., rocky/vm
              
              # Get the name of the build context directory
              current_dir_name=$(basename "$context_dir") # e.g., vm
              
              # Get the path of the parent directory
              parent_dir_path=$(dirname "$context_dir") # e.g., rocky
              
              image_name=""
              image_tag=""

              # Check if we are in a top-level directory (parent is '.')
              if [ "$parent_dir_path" = "." ]; then
                  # This is a main folder (e.g., debian)
                  image_name="$current_dir_name"
                  image_tag="latest"
              else
                  # This is a subdir (e.g., rocky/vm)
                  # Parent's name is the basename of the parent path
                  image_name=$(basename "$parent_dir_path")
                  image_tag="$current_dir_name"
              fi
              
              # This is the final image name and tag (e.g., rocky:vm)
              image_tag_local="${image_name}:${image_tag}"
              
              # This is the full URL for the registry (e.g., gitea.example.com/owner/rocky:vm)
              IMAGE_URL="${REGISTRY_BASE}/${image_name}:${image_tag}"
              echo ""
              echo "================================================="
              echo "Found:      $cfile_clean"
              echo "Context:    $context_dir"
              echo "Building:   $IMAGE_URL"
              echo "================================================="
              
              # Build the image and tag it with the full registry URL
              podman build -t "$IMAGE_URL" -f "$cfile_clean" "$context_dir"
              
              echo "Pushing $IMAGE_URL"
              podman push "$IMAGE_URL"
              echo "================================================="
              echo ""
          done
          
          echo "All builds complete."
