FROM tea.intra.kat.sh/koa/rocky:vm

RUN export MUNGEUSER=1001 && \
    groupadd -g $MUNGEUSER munge && \
    useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge \ 
        -u $MUNGEUSER -g munge -s /sbin/nologin munge

RUN dnf -y update && dnf -y install --allowerasing \
    gcc \
    gcc-c++ \
    tar \
    make \
    perl \
    lbzip2 \
    bzip2 \
    python3 \
    openssl \
    openssl-devel \
    pam-devel \
    autoconf \
    automake \
    numactl \
    numactl-devel \
    rpm-build \
    hwloc \
    hwloc-devel \
    lua \
    lua-devel \
    readline-devel \
    rrdtool-devel \
    ncurses-devel \
    man2html \
    libibmad \
    libibumad \
    libevent \
    libevent-devel \
    munge  \
    munge-libs      \
    munge-devel && \
    dnf clean all

RUN mkdir -p /etc/munge /var/log/munge /var/lib/munge /run/munge
RUN chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/ && \
    chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/ && \
    chmod 0711 /run/munge/

