FROM tea.intra.kat.sh/koa/rocky:latest

# install config manager and setup epel
RUN dnf -y update && \
	dnf -y install --allowerasing 'dnf-command(config-manager)' epel-release && \
	dnf config-manager --set-enabled crb

# gpu drivers
RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64/cuda-rhel10.repo
RUN dnf -y install --setopt=install_weak_deps=False --allowerasing \
	cuda-drivers \
	datacenter-gpu-manager-4-proprietary \
	datacenter-gpu-manager-4-core \
	nvidia-driver

# Gnome
RUN dnf -y install --setopt=install_weak_deps=False \
	google-noto-sans-fonts \
	google-noto-emoji-fonts \
	google-noto-cjk-fonts
RUN dnf -y group install --setopt=install_weak_deps=False "base-graphical"
RUN dnf -y group install --setopt=install_weak_deps=False "GNOME"

# qol
RUN dnf -y install --setopt=install_weak_deps=False \
	openssl \
	firefox \
	git \
	steam-devices

# xpad
RUN dnf -y install --setopt=install_weak_deps=False \
	kernel-devel \
	kernel-headers \
	kmod

RUN git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
RUN dkms install -m xpad -v 0.4 --kernelsourcedir /lib/modules/$(dnf repoquery -q --latest-limit=1 kernel-core --queryformat "%{version}-%{release}.%{arch}")/build 

RUN echo xpad > /etc/modules-load.d/xpad.conf

	

# Setup dracut
RUN dnf -y install --setopt=install_weak_deps=False ignition gdisk
RUN dnf -y install https://github.com/warewulf/warewulf/releases/download/v4.6.4/warewulf-dracut-4.6.4-1.el10.noarch.rpm
RUN echo 'install_items+=" /usr/sbin/sgdisk "' > /etc/dracut.conf.d/ignition-extras.conf
RUN dracut --force --no-hostonly --add wwinit --add ignition --regenerate-all

RUN dnf clean all
