FROM tea.intra.kat.sh/koa/rocky:nvidia

RUN export MUNGEUSER=1001 && \
    groupadd -g $MUNGEUSER munge && \
    useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge \ 
        -u $MUNGEUSER -g munge -s /sbin/nologin munge

RUN export SLURMUSER=1002 && \
    groupadd -g $SLURMUSER slurm && \
    useradd -m -c "SLURM workload manager" -d /var/lib/slurm \
        -u $SLURMUSER -g slurm -s /bin/bash slurm && \
    mkdir /var/log/slurm && \
    chown slurm:slurm /var/log/slurm


RUN dnf config-manager --add-repo https://tea.intra.kat.sh/api/packages/koa/rpm/rocky/el10.repo && \
    dnf -y update && dnf -y install --setopt=install_weak_deps=False --allowerasing \
    python3 \
    openssl \
    numactl \
    numactl-devel \
    hwloc \
    lua \
    lua-devel \
    rrdtool-devel \
    ncurses-devel \
    libibmad \
    libibumad \
    libevent \
    munge && \
    dnf -y install --nogpgcheck --setopt=install_weak_deps=False --allowerasing \
    slurm \
    slurm-perlapi \
    slurm-slurmd \
    && \
    dnf clean all

RUN mkdir -p /etc/munge /var/log/munge /var/lib/munge /run/munge
RUN chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/ && \
    chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/ && \
    chmod 0711 /run/munge/

RUN systemctl enable munge
RUN systemctl enable slurmd