FROM tea.intra.kat.sh/koa/debian:latest

RUN sed -i 's/Components: main/Components: main non-free-firmware contrib non-free/g' /etc/apt/sources.list.d/debian.sources
RUN cat /etc/apt/sources.list.d/debian.sources
RUN apt-get update && apt-get upgrade -y && apt-get install -y xfce4 xfce4-goodies 
RUN apt-get install -y linux-headers-amd64 build-essential dkms
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y nvidia-driver nvidia-kernel-dkms firmware-misc-nonfree steam-installer
RUN rm -rf /var/lib/apt/lists/*
